# generated by running: $: python get_consis_etfs.py > settings_indices.py
indices = {'FETH', 'SHLD', 'BITB', 'FBTC', 'MAGS', 'TECL', 'ETHA', 'TQQQ', 'GRNY', 'ARKB', 'SPXL', 'ETH', 'IBIT', 'BAI', 'FNGU'}
