# generated by running: $: python get_consis_etfs.py > settings_indices.py
indices = {'GRNY', 'ETH', 'BAI', 'TQQQ', 'IBIT', 'SHLD', 'FETH', 'FBTC', 'ARKB', 'ETHA', 'FNGU', 'MAGS', 'BITB', 'TECL', 'SPXL'}
