# Streamlit 密钥配置示例文件
# 
# 1. 将此文件复制并重命名为 'secrets.toml'
# 2. 填写您的实际API密钥
# 3. 确保 'secrets.toml' 已添加到 .gitignore 文件中（已配置）
# 4. 不要将包含实际密钥的文件提交到版本控制系统

# Gemini API 配置
[gemini]
api_key = "您的Gemini API密钥"

# 千问 API 配置
[qianwen]
api_key = "您的千问API密钥"

# 其他可能需要的API密钥
#[other_service]
#api_key = "您的其他服务API密钥"

# 在代码中访问密钥的方式：
# import streamlit as st
# gemini_key = st.secrets["gemini"]["api_key"]
# qianwen_key = st.secrets["qianwen"]["api_key"]